services:
  # Backend Service
  - type: web
    name: jobportal-backend
    runtime: node
    region: oregon
    plan: free
    branch: main
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 8000
      - key: MONGO_URI
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: CLOUD_NAME
        sync: false
      - key: API_KEY
        sync: false
      - key: API_SECRET
        sync: false
      - key: FRONTEND_URL
        sync: false

  # Frontend Service
  - type: web
    name: jobportal-frontend
    runtime: static
    region: oregon
    plan: free
    branch: main
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_API_URL
        sync: false
